# -*- coding: utf-8 -*-
"""adult_data.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bQK1PFg5EENKCvOGG3jh6M9NuTUaXiFd
"""

from google.colab import drive
drive.mount('/content/drive')

#1 people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (race column)
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/adult.data.csv') 
#count the number of people in each race
race_count = df['race'].value_counts()
print(race_count)

#2 Average age of men 

men_age = df[df['sex'] == 'Male']['age']
average_age = men_age.mean()

print("Average Age: " ,average_age)

#3  the percentage of people who have a Bachelor's degree?

num_bachelor_degree_ = len(df[df['education']=='Bachelors']) 
total_people = len(df) 
percentage = (num_bachelor_degree_/total_people)*100

print("number of bachelor degree holders : " , num_bachelor_degree_)
print("total people :" , total_people)
print(percentage , "%")

#4 percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?

advanced_education = df[(df['education'] == 'Bachelors') | (df['education'] == 'Masters') | (df['education'] == 'Doctorate')]
high_salary = len(advanced_education[advanced_education['salary'] == '>50K'])
percentage = (high_salary/len(advanced_education))*100
print(high_salary)
print(len(advanced_education))
print("People with advanced education and high salary: " ,percentage ,"%")

#5  percentage of people without advanced education make more than 50K?
bachelors = df['education'].loc[(df['education'] == 'Bachelors') & (df['salary'] == '>50K')].count()
masters = df['education'].loc[(df['education'] == 'Masters') & (df['salary'] == '>50K')].count()
doctorate = df['education'].loc[(df['education'] == 'Doctorate') & (df['salary'] == '>50K')].count()

adv_edu = bachelors + masters + doctorate
total = df['age'].count()
adv_edu_percent = (adv_edu/total)*100

print(adv_edu_percent.round(decimals = 2))

#6  the minimum number of hours a person works per week?
not_adv_edu = df['education'].loc[(df['education'] != 'Bachelors') & (df['education'] != 'Masters')& (df['education'] != 'Doctorate') & (df['salary'] == '>50K')].count()
total = df['age'].count()
not_adv_edu_percent = (not_adv_edu/total)*100

print(not_adv_edu_percent.round(decimals = 2))

#7percentage of the people who work the minimum number of hours per week have a salary of more than 50K?
minimum_hours = df['hours-per-week']

print(minimum_hours.min())

#8 country has the highest percentage of people that earn >50K and what is that percentage?
country_percentages = df[df['salary'] == '>50K']['native-country'].value_counts(normalize=True) * 100
print(country_percentages)

#9.Identify the most popular occupation for those who earn >50K in India.
india_high_earners = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]

popular_occupation = india_high_earners['occupation'].value_counts()
print(popular_occupation)
print("Most Popular Occupation among indians : " ,popular_occupation.idxmax())